spring:
  datasource:
    druid:
      driver-class-name : com.mysql.jdbc.Driver
      url : jdbc:mysql://localhost:3306/2019011302?characterEncoding = utf-8
      username : root
      password : 12345
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.mall.entity